server:
  port: 3000
spring:
  application:
    name: ecommerce
  datasource:
    url: jdbc:mysql://localhost:3306/doAn?serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: springstudent
    password: springstudent
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 10000000
    expiration-refresh-token: 80000000