server:
  port: 3000

spring:
  application:
    name: ecommerce
  datasource:
    url: jdbc:mysql://mysql8-container:3306/ecommercedb?serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: kien0702
  data:
    redis:
      host: redis-container
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  main:
    banner-mode: off
  mail:
    host: smtp.gmail.com
    port: 587
    username: khanhquocphamdev@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 10000000
    expiration-refresh-token: 80000000

logging:
  level:
    root: INFO
    com.ghtk.ecommercewebsite: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

cloudinary:
  upload:
    file:
      cloud-name: dqgarzqlx
      api-key: 889522243963762
      api-secret: ${CLOUDINARY_SECRET_KEY}

stripe:
  api:
    key: ${STRIPE_API_KEY}

payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    createOrderUrl: https://sandbox.vnpayment.vn/merchant_webapi/merchant.html
    tmnCode: ${PAYMENT_TMN_CODE}
    secretKey: ${PAYMENT_KEY}
    returnUrl: http://localhost:3000/api/payments/vn-pay-callback
    version: 2.1.0
    command: pay
    orderType: other
