server:
  port: 3000
spring:
  application:
    name: ecommerce
  datasource:
    url: jdbc:mysql://localhost:3306/doAn?serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1235
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


security:
  jwt:
    secret-key: 695769324F787162696C62336E5A354E67585A2F6E336C344737526D6A6954753033533436336D315471513D
    expiration-time: 10000000
    expiration-refresh-token: 80000000